server:
  port: ${SERVER_PORT}
spring:
  application:
    name: OrderApplication
  main:
    bannerMode: off
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    show_sql: true
    format_sql: true
logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
  # Logging level pattern
  pattern:
    console: '${LOG_LEVEL_PATTERN:-%5p} %m%n'
# Actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'